@echo ¸´ÖÆÎÄ¼þ
echo copy src files...
xcopy eclipse\AMapLocationDemo\src android_studio\AMapLocationDemo\app\src\main\java /Y /E
echo copy res files...
xcopy eclipse\AMapLocationDemo\res android_studio\AMapLocationDemo\app\src\main\res /Y/E
echo copy AndroidManifest.xml...
xcopy eclipse\AMapLocationDemo\AndroidManifest.xml android_studio\AMapLocationDemo\app\src\main\AndroidManifest.xml /Y
echo del studio libs...
del android_studio\AMapLocationDemo\app\libs\*.jar
echo copy libs...
xcopy eclipse\AMapLocationDemo\libs android_studio\AMapLocationDemo\app\libs /Y/E
echo finished
@pause
