@echo ¸´ÖÆÎÄ¼þ
echo copy src files...
xcopy android_studio\AMapLocationDemo\app\src\main\java eclipse\AMapLocationDemo\src /Y /E
echo copy res files...
xcopy android_studio\AMapLocationDemo\app\src\main\res eclipse\AMapLocationDemo\res /Y/E
echo copy AndroidManifest.xml...
xcopy android_studio\AMapLocationDemo\app\src\main\AndroidManifest.xml eclipse\AMapLocationDemo\AndroidManifest.xml /Y
echo del eclipse libs...
del eclipse\AMapLocationDemo\libs\*.jar
echo copy libs...
xcopy android_studio\AMapLocationDemo\app\libs eclipse\AMapLocationDemo\libs /Y/E
echo finished
@pause
